import React, { useState, useRef, useEffect } from 'react';
import { ArrowRight, ArrowUpRight, UsersThree, FileText, Cube, ChatCircleDots, Database, Robot, ChartBar, LinkSimple, House, MagnifyingGlass, X, List, CheckCircle, Play, ShieldCheck, Sparkle, DownloadSimple } from '@phosphor-icons/react';
import { ResponsiveContainer, AreaChart, Area, XAxis, CartesianGrid, Tooltip } from 'recharts';

const products = [
  { title:'AI 智能客服', short:'让每一次对话，都有回应', icon:ChatCircleDots, desc:'连接企业知识与服务场景，帮助客户快速找到答案，让团队专注更有价值的沟通。', tags:['多轮问答','人工协同','服务记录'] },
  { title:'企业知识库', short:'让企业知识，成为生产力', icon:Database, desc:'将散落在文档中的经验汇聚成可检索、可问答的企业知识，帮助团队更快找到所需信息。', tags:['文档管理','知识检索','来源追溯'] },
  { title:'AI Agent', short:'从理解需求，到协同执行', icon:Robot, desc:'围绕具体业务任务编排智能体，将信息检索、内容生成与流程协作连接起来。', tags:['任务编排','工具连接','人机协作'] },
  { title:'智能办公', short:'把时间，留给更重要的事', icon:FileText, desc:'从会议纪要到文案初稿，辅助处理重复工作，让想法更快形成成果。', tags:['内容生成','会议摘要','文档辅助'] },
  { title:'数据分析', short:'从业务数据，发现新机会', icon:ChartBar, desc:'通过自然语言探索业务数据，以直观的分析结果辅助团队理解变化、发现机会。', tags:['自然语言查询','可视化分析','业务洞察'] },
  { title:'系统集成', short:'连接更多系统，释放协同力', icon:LinkSimple, desc:'围绕现有业务系统设计连接方式，让智能能力融入已有工作流程。', tags:['接口连接','业务协同','流程整合'] },
];
const industries = [
 {name:'金融行业',icon:ShieldCheck,photo:0,headline:'让专业服务，更及时地抵达客户。',text:'围绕业务资料检索、客户常见问题和内部流程协作，探索可追溯的智能辅助场景。',scenes:['产品资料问答','内部知识助手','服务流程辅助']},
 {name:'政企单位',icon:House,photo:1,headline:'连接信息与服务，让协作更顺畅。',text:'整合办事指南与内部知识，为咨询答复、资料查找和日常办公提供智能支持。',scenes:['办事指南问答','公文整理辅助','内部知识检索']},
 {name:'零售电商',icon:Cube,photo:2,headline:'从购买前到售后，连接每一次体验。',text:'将商品知识、服务流程与客户问题连接起来，辅助团队提供连贯的购物服务。',scenes:['商品知识问答','售后问题分流','营销文案辅助']},
 {name:'医疗健康',icon:UsersThree,photo:3,headline:'让服务信息，更易获取与理解。',text:'聚焦就医流程、服务指南与内部资料查询，为非诊疗服务提供信息支持。',scenes:['就医流程指引','服务事项查询','内部资料检索']},
];
const trend = [32,47,40,67,58,74,69].map((value,i)=>({day:['周一','周二','周三','周四','周五','周六','周日'][i],value}));
function Brand({light=false}) { return <a className={'brand '+(light?'light':'')} href="#home" aria-label="众达AI 首页"><img src="/assets/logo.png" alt=""/><strong>众达AI</strong></a> }
function Dashboard({expanded=false}) {
 const [active,setActive]=useState(0);
 const tabs=[{title:'工作台',icon:House},{title:'对话中心',icon:ChatCircleDots},{title:'知识库',icon:Database},{title:'智能体',icon:Robot}];
 const [query,setQuery]=useState('');
 const docs=['客户服务常见问题.pdf','企业产品介绍.pdf','团队协作指南.pdf'];
 return <div className={'dashboard '+(expanded?'expanded':'')}>
  <aside className="dash-sidebar"><Brand light/><div className="workspace-label">企业工作空间</div>{tabs.map((t,i)=><button key={t.title} onClick={()=>setActive(i)} aria-pressed={active===i} className={active===i?'selected':''}><t.icon size={16}/><span>{t.title}</span></button>)}<div className="sidebar-bottom"><ShieldCheck size={16}/><span>连接每一份价值</span></div></aside>
  <div className="dash-body"><div className="dash-top"><span>众达 AI 企业服务平台</span><span className="demo-label">交互演示 · 示例数据</span></div><div className="dash-content">
  {active===0?<><div className="dash-greeting"><div><h3>你好，欢迎使用众达AI</h3><p>让智能成为每一个业务的助力。</p></div><Sparkle size={26} weight="duotone"/></div><div className="dash-metrics">{[['今日对话','1,286'],['知识文档','328'],['运行中智能体','12']].map(([label,value])=><div key={label}><span>{label}</span><strong>{value}</strong><small>示例数据</small></div>)}</div><div className="dash-chart"><div className="chart-title"><strong>服务互动趋势</strong><span>最近 7 天</span></div><ResponsiveContainer width="100%" height={expanded?190:126}><AreaChart data={trend} margin={{top:16,right:8,bottom:0,left:8}}><CartesianGrid vertical={false} stroke="#e8eef6"/><XAxis dataKey="day" tick={{fontSize:10,fill:'#8b98aa'}} axisLine={false} tickLine={false}/><Tooltip formatter={v=>[v,'互动量（示例）']} /><Area type="monotone" dataKey="value" stroke="#2679ff" fill="#edf4ff" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></>:
  active===1?<div className="dash-module"><ChatCircleDots size={32} color="#1767ff"/><h3>让问题，更快找到答案</h3><p>试试向服务助手提一个问题。</p><div className="chat-example"><strong>如何开始使用企业知识库？</strong><p>先整理企业常用资料，再在知识库中上传文档。解析完成后，即可在对话中检索相关内容。</p><small>预设对话示例</small></div><button className="text-link" onClick={()=>setActive(2)}>查看知识库 <ArrowRight/></button></div>:
  active===2?<div className="dash-module"><h3>企业知识库</h3><label className="dash-search"><MagnifyingGlass/><input aria-label="搜索示例文档" placeholder="搜索示例文档" value={query} onChange={e=>setQuery(e.target.value)}/></label>{docs.filter(d=>d.includes(query)).map(d=><div className="document-row" key={d}><FileText size={22}/><span>{d}</span><small>已就绪</small></div>)}{!docs.some(d=>d.includes(query))&&<p className="empty">没有找到相关文档，请换个关键词。</p>}</div>:
  <div className="dash-module"><h3>你的智能协作团队</h3><p>为具体任务，找到合适的助手。</p>{['客户服务助手','知识检索助手','办公文案助手'].map(t=><div className="document-row" key={t}><Robot size={24}/><span>{t}</span><small>演示中</small></div>)}</div>}
  </div></div>
 </div>
}
function Modal({children,onClose,wide=false,title}) {
 const ref=useRef(null);
 useEffect(()=>{const prev=document.activeElement;ref.current.showModal();document.body.style.overflow='hidden';return()=>{document.body.style.overflow='';prev?.focus();}},[]);
 return <dialog ref={ref} className={wide?'modal modal-wide':'modal'} onCancel={e=>{e.preventDefault();onClose()}} onClick={e=>{if(e.target===ref.current)onClose()}} aria-label={title}><button className="close-button" aria-label="关闭弹窗" onClick={onClose}><X size={22}/></button>{children}</dialog>
}
function Contact() {
 const [summary,setSummary]=useState('');
 function submit(e){e.preventDefault();const f=new FormData(e.target);setSummary(`众达AI · 合作咨询需求\n\n称呼：${f.get('name')}\n企业：${f.get('company')}\n联系邮箱：${f.get('email')}\n关注方向：${f.get('type')}\n需求描述：${f.get('message')}`)}
 function download(){const url=URL.createObjectURL(new Blob([summary],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='众达AI-咨询需求.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <><span className="eyebrow">LET’S CONNECT</span><h2>一起，让想法落地。</h2><p className="modal-intro">告诉我们你的业务场景，探索适合你的智能应用。</p>{summary?<div className="contact-result"><CheckCircle size={40} color="#1767ff"/><h3>咨询需求已整理</h3><p>当前为网站预览，尚未发送给众达AI。你可以下载需求摘要，供后续沟通使用。</p><pre>{summary}</pre><button className="primary" onClick={download}><DownloadSimple/>下载需求摘要</button><button className="text-link" onClick={()=>setSummary('')}>重新填写</button></div>:<form onSubmit={submit}><div className="form-grid"><label>你的称呼<input required name="name" maxLength={50} placeholder="怎么称呼你"/></label><label>企业名称<input required name="company" maxLength={100} placeholder="请输入企业名称"/></label></div><label>联系邮箱<input required type="email" name="email" placeholder="name@company.com"/></label><label>关注方向<select name="type">{products.map(p=><option key={p.title}>{p.title}</option>)}<option>其他合作需求</option></select></label><label>需求描述<textarea required name="message" maxLength={1000} placeholder="例如：希望让客户更快找到产品与售后信息……" rows={3}/></label><p className="form-note">此预览仅生成可下载的需求摘要，不会上传或发送你的信息。</p><button className="primary" type="submit">生成咨询需求 <ArrowRight/></button></form>}</>
}
export function App(){
 const [menu,setMenu]=useState(false),[modal,setModal]=useState(null),[industry,setIndustry]=useState(0);
 const chosen=industries[industry];
 const nav=[['home','首页'],['products','产品能力'],['solutions','解决方案'],['about','关于我们']];
 return <><header><div className="nav-shell"><Brand/><nav className={menu?'is-open':''} aria-label="主导航">{nav.map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}</a>)}<button className="nav-contact" onClick={()=>{setMenu(false);setModal('contact')}}>联系我们</button></nav><button className="primary nav-demo" onClick={()=>setModal('demo')}>体验产品演示 <ArrowUpRight size={16}/></button><button className="menu-button" aria-expanded={menu} aria-label={menu?'关闭导航':'打开导航'} onClick={()=>setMenu(!menu)}>{menu?<X/>:<List/>}</button></div></header>
 <main><section className="hero" id="home"><img className="hero-art" src="/assets/hero.png" alt="蓝色玻璃质感的众达AI连接标志"/><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">众人连接 · 通达服务 · 智能应用</p><h1>连接人与智能<br/>让服务更高效<span>。</span></h1><p className="hero-description">让 AI 融入真实业务，连接每一份知识与服务。<br className="desktop-break"/>与众达AI一起，探索企业智能化的更多可能。</p><div className="hero-actions"><a href="#solutions" className="primary">了解解决方案 <ArrowRight size={18}/></a><button className="secondary" onClick={()=>setModal('contact')}>联系我们 <ArrowUpRight size={17}/></button></div><div className="hero-footnote"><span>CONNECT PEOPLE. ENABLE INTELLIGENCE.</span></div></div><div className="hero-caption"><span>以连接，创造价值</span><small>CONNECTED INTELLIGENCE</small></div></div></section>
 <section className="pillars container" aria-label="品牌理念">{[{icon:UsersThree,title:'众人连接',text:'连接员工、客户与伙伴，构建协作网络。'},{icon:FileText,title:'通达服务',text:'连接业务与服务流程，让服务触手可及。'},{icon:Cube,title:'智能应用',text:'将 AI 能力融入场景，创造实际价值。'}].map((p,i)=><div className="pillar" key={p.title}><p.icon size={34} weight="duotone"/><div><h3>{p.title}</h3><p>{p.text}</p></div><small>0{i+1}</small></div>)}</section>
 <section id="products" className="products container section"><div className="section-heading"><div><span className="eyebrow">OUR CAPABILITIES</span><h2>每一种能力，都为业务而来。</h2></div><p>从一次对话，到一套工作流<br/>用适合的智能能力，回应真实需求。</p></div><div className="product-grid">{products.map((p,i)=><button className="product-card" key={p.title} onClick={()=>setModal(i)}><span className="product-icon"><p.icon size={29} weight="duotone"/></span><h3>{p.title}</h3><p>{p.short}</p><span className="card-bottom"><span>探索能力</span><ArrowUpRight size={18}/></span></button>)}</div></section>
 <section className="showcase container" id="platform"><div className="showcase-copy"><span className="eyebrow">ONE PLATFORM. MORE POSSIBILITIES.</span><h2>一站式企业<br/>AI 服务平台</h2><p>从对话服务到业务协作，<br/>让智能连接每一个工作场景。</p><button className="primary" onClick={()=>setModal('demo')}><Play size={17} weight="fill"/>体验产品演示</button><span className="showcase-note">点击右侧菜单，探索平台能力</span></div><div className="dashboard-wrap"><Dashboard/></div></section>
 <section className="solutions container section" id="solutions"><div className="section-heading"><div><span className="eyebrow">BUILT FOR YOUR INDUSTRY</span><h2>深入场景，让智能有用。</h2></div><p>理解每个行业的不同<br/>寻找技术与业务的契合点。</p></div><div className="industry-tabs" role="tablist" aria-label="行业解决方案">{industries.map((s,i)=><button key={s.name} id={'industry-tab-'+i} role="tab" aria-selected={industry===i} aria-controls="industry-panel" tabIndex={industry===i?0:-1} onKeyDown={e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?3:(industry+(e.key==='ArrowRight'?1:3))%4;setIndustry(next);document.getElementById('industry-tab-'+next)?.focus()}}} onClick={()=>setIndustry(i)} className={industry===i?'active':''}><s.icon size={24}/><span>{s.name}</span><ArrowUpRight size={18}/></button>)}</div><div className="industry-panel" role="tabpanel" id="industry-panel" aria-labelledby={'industry-tab-'+industry}><div className={'industry-photo photo-'+chosen.photo} role="img" aria-label={chosen.name+'场景照片'}/><div className="industry-copy"><span className="eyebrow">{chosen.name} / 场景探索</span><h3>{chosen.headline}</h3><p>{chosen.text}</p><div className="scene-tags">{chosen.scenes.map(s=><span key={s}><CheckCircle size={16}/>{s}</span>)}</div><button className="text-link" onClick={()=>setModal('contact')}>聊聊你的业务场景 <ArrowRight size={18}/></button></div></div></section>
 <section className="about" id="about"><div className="container about-inner"><div><span className="eyebrow">ABOUT ZHONGDA AI</span><h2>技术的价值，<br/>在于人与服务的连接。</h2></div><div><p>众达AI，以「众人连接、通达服务、智能应用」为理念，探索人工智能与企业业务的融合。</p><p>我们相信，好的智能应用从理解真实需求开始，让知识被找到，让协作更顺畅，让服务更高效。</p><button className="text-link" onClick={()=>setModal('contact')}>与我们交流 <ArrowRight size={18}/></button></div></div></section>
 <section className="contact-banner container"><div><span className="eyebrow">YOUR NEXT CHAPTER</span><h2>让更好的工作方式，从这里开始。</h2></div><button className="primary" onClick={()=>setModal('contact')}>开启合作对话 <ArrowUpRight size={19}/></button></section></main>
 <footer className="container"><Brand/><p>众人连接 · 通达服务 · 智能应用</p><small>© {new Date().getFullYear()} 众达AI</small><a href="#home" aria-label="返回顶部">回到顶部 <ArrowUpRight/></a></footer>
 {modal!==null&&<Modal onClose={()=>setModal(null)} title={modal==='contact'?'联系众达AI':modal==='demo'?'产品交互演示':products[modal].title} wide={modal==='demo'}>{modal==='contact'?<Contact/>:modal==='demo'?<><span className="eyebrow">EXPLORE THE PLATFORM</span><h2>智能工作，从这里开始。</h2><p className="modal-intro">切换菜单体验平台。所有数据与对话均为本地演示内容。</p><Dashboard expanded/></>:<><span className="product-icon modal-icon">{React.createElement(products[modal].icon,{size:34,weight:'duotone'})}</span><span className="eyebrow">OUR CAPABILITIES / 0{modal+1}</span><h2>{products[modal].title}</h2><p className="modal-intro">{products[modal].desc}</p><div className="feature-tags">{products[modal].tags.map(t=><span key={t}><CheckCircle size={18}/>{t}</span>)}</div><button className="primary" onClick={()=>setModal('contact')}>咨询应用场景 <ArrowRight/></button></>}</Modal>}
 </>
}
